/*
 Piwik - free/libre analytics platform

 JavaScript tracking client

 @link http://piwik.org
 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license http://piwik.org/free-software/bsd/ BSD-3 Clause (also in ./LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
 @license-end */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(l,k,m){l instanceof String&&(l=String(l));for(var u=l.length,p=0;p<u;p++){var G=l[p];if(k.call(m,G,p,l))return{i:p,v:G}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(l,k,m){if(l==Array.prototype||l==Object.prototype)return l;l[k]=m.value;return l};$jscomp.getGlobal=function(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<l.length;++k){var m=l[k];if(m&&m.Math==Math)return m}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(l,k){var m=$jscomp.propertyToPolyfillSymbol[k];if(null==m)return l[k];m=l[m];return void 0!==m?m:l[k]};
$jscomp.polyfill=function(l,k,m,u){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(l,k,m,u):$jscomp.polyfillUnisolated(l,k,m,u))};$jscomp.polyfillUnisolated=function(l,k,m,u){m=$jscomp.global;l=l.split(".");for(u=0;u<l.length-1;u++){var p=l[u];if(!(p in m))return;m=m[p]}l=l[l.length-1];u=m[l];k=k(u);k!=u&&null!=k&&$jscomp.defineProperty(m,l,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(l,k,m,u){var p=l.split(".");l=1===p.length;u=p[0];u=!l&&u in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var G=0;G<p.length-1;G++){var B=p[G];if(!(B in u))return;u=u[B]}p=p[p.length-1];m=$jscomp.IS_SYMBOL_NATIVE&&"es6"===m?u[p]:null;k=k(m);null!=k&&(l?$jscomp.defineProperty($jscomp.polyfills,p,{configurable:!0,writable:!0,value:k}):k!==m&&(void 0===$jscomp.propertyToPolyfillSymbol[p]&&(m=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[p]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(p):$jscomp.POLYFILL_PREFIX+m+"$"+p),$jscomp.defineProperty(u,$jscomp.propertyToPolyfillSymbol[p],{configurable:!0,writable:!0,value:k})))};$jscomp.polyfill("Array.prototype.find",function(l){return l?l:function(k,m){return $jscomp.findInternal(this,k,m).v}},"es6","es3");
$jscomp.checkStringArgs=function(l,k,m){if(null==l)throw new TypeError("The 'this' value for String.prototype."+m+" must not be null or undefined");if(k instanceof RegExp)throw new TypeError("First argument to String.prototype."+m+" must not be a regular expression");return l+""};
$jscomp.polyfill("String.prototype.endsWith",function(l){return l?l:function(k,m){var u=$jscomp.checkStringArgs(this,k,"endsWith");k+="";void 0===m&&(m=u.length);m=Math.max(0,Math.min(m|0,u.length));for(var p=k.length;0<p&&0<m;)if(u[--m]!=k[--p])return!1;return 0>=p}},"es6","es3");
Array.prototype.forEach||(Array.prototype.forEach=function(l,k){var m;if(null==this)throw new TypeError(" this is null or not defined");var u=Object(this),p=u.length>>>0;if("[object Function]"!={}.toString.call(l))throw new TypeError(l+" is not a function");k&&(m=k);for(k=0;k<p;){if(k in u){var G=u[k];l.call(m,G,k,u)}k++}});
var searchIntervalId=searchIntervalId||0,searchIntervalCount=searchIntervalId||0,DcmAn={addListener:function(l,k,m){l.addEventListener?l.addEventListener(k,m,{passive:!0}):l.attachEvent&&l.attachEvent("on"+k,m)},addFormEvent:function(){var l=document.getElementsByTagName("form");for(i=0;i<l.length;i++)DcmAn.addListener(l[i],"submit",DcmAn.decorateMe)},addEvent:function(){var l=document.getElementsByTagName("a");for(i=0;i<l.length;i++)DcmAn.addListener(l[i],"mousedown",DcmAn.decorateMe),DcmAn.addListener(l[i],
"keyup",DcmAn.decorateMe),DcmAn.addListener(l[i],"touchstart",DcmAn.decorateMe)},decorateMe:function(l){l=l||window.event;if((l=l.target||l.srcElement)&&l.href)DcmAn.checkDomain(l.href)&&(l.href=DcmAn.decorateDmpfCross(l.href));else if(l&&l.action&&DcmAn.checkDomain(l.action))if("get"==l.method){var k=DcmAn.getDaCookieId();if(1<k.length){var m=document.createElement("input");m.type="hidden";m.name="dcmancr";m.value=DcmAn.makeCrossParam(k);l.appendChild(m)}}else l.action=DcmAn.decorateDmpfCross(l.action)},
checkDomain:function(l){var k=!1;_dcmlinker.forEach(function(m){var u=l.match(/^https?:\/\/([^\/:]+)/);null!=u&&u[1]==m&&(k=!0)});return k},decorateDmpfCross:function(l){var k=DcmAn.getDaCookieId();if(1<k.length){var m=l.split("#");l=m[0];k=DcmAn.makeCrossParam(k);var u=l.split("?");if(1==u.length)l=l+"?dcmancr="+k;else{u=u[1].split("&");var p=!0;for(i=0;i<u.length;i++)if(0==u[i].indexOf("dcmancr=")){p=!1;break}p&&(l=l+"&dcmancr="+k)}1<m.length&&(l=l+"#"+m[1])}return l},makeCrossParam:function(l){for(var k=
l.length,m=0,u=(new Date).getTime(),p=0;p<k;p++)m+=l.charCodeAt(p);k=DcmAn.getGaCookieId();p=DcmAn.makeUa();return l+"."+u+"."+p+"."+(m+u+p)+(k?"_"+k+"_"+Piwik.getAsyncTracker().getSiteId():"")},getDaCookieId:function(){if(window.navigator.cookieEnabled&&document.cookie)for(var l=document.cookie.split("; "),k=0;k<l.length;k++){var m=l[k].split("=");if("daxtr"==m[0])return m[1].split(".")[0]}return""},getGaCookieId:function(){if(window.navigator.cookieEnabled&&document.cookie){var l=/(^|;)[ ]*_ga=([^;]*)/.exec(document.cookie);
if((l=l?l[2]:"")&&l.match(/.*\.\d+\.(\d+\.\d+)/))return RegExp.$1}return 0},makeUa:function(){for(var l=navigator.userAgent.length,k=0,m=0;m<l;m++)k+=navigator.userAgent.charCodeAt(m);return k}};"object"!==typeof JSON2&&(JSON2=window.JSON||{});
(function(){function l(y){if("undefined"!=typeof window.addEventListener){var H=document.readyState;"interactive"==H||"complete"==H||"loaded"==H?y():document.addEventListener("DOMContentLoaded",y,!1)}else"undefined"!=typeof window.attachEvent&&(window.attachEvent("onload",y),y())}function k(y){return 10>y?"0"+y:y}function m(y){ma.lastIndex=0;return ma.test(y)?'"'+y.replace(ma,function(H){var T=Ya[H];return"string"===typeof T?T:"\\u"+("0000"+H.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+y+'"'}
function u(y,H){var T=U,z=H[y];if(z&&"object"===typeof z){var ba=Object.prototype.toString.apply(z);z="[object Date]"===ba?isFinite(z.valueOf())?z.getUTCFullYear()+"-"+k(z.getUTCMonth()+1)+"-"+k(z.getUTCDate())+"T"+k(z.getUTCHours())+":"+k(z.getUTCMinutes())+":"+k(z.getUTCSeconds())+"Z":null:"[object String]"===ba||"[object Number]"===ba||"[object Boolean]"===ba?z.valueOf():"[object Array]"!==ba&&"function"===typeof z.toJSON?z.toJSON(y):z}"function"===typeof X&&(z=X.call(H,y,z));switch(typeof z){case "string":return m(z);
case "number":return isFinite(z)?String(z):"null";case "boolean":case "null":return String(z);case "object":if(!z)return"null";U+=Ha;var R=[];if("[object Array]"===Object.prototype.toString.apply(z)){ba=z.length;for(y=0;y<ba;y+=1)R[y]=u(y,z)||"null";H=0===R.length?"[]":U?"[\n"+U+R.join(",\n"+U)+"\n"+T+"]":"["+R.join(",")+"]";U=T;return H}if(X&&"object"===typeof X)for(ba=X.length,y=0;y<ba;y+=1){if("string"===typeof X[y]){var M=X[y];(H=u(M,z))&&R.push(m(M)+(U?": ":":")+H)}}else for(M in z)Object.prototype.hasOwnProperty.call(z,
M)&&(H=u(M,z))&&R.push(m(M)+(U?": ":":")+H);H=0===R.length?"{}":U?"{\n"+U+R.join(",\n"+U)+"\n"+T+"}":"{"+R.join(",")+"}";U=T;return H}}l(DcmAn.addEvent);l(DcmAn.addFormEvent);var p="",G=location.href,B=G.split("?dcmancr=");2==B.length?p=-1!=B[1].indexOf("&")?B[1].split("&")[0]:B[1]:(B=G.split("&dcmancr="),2==B.length&&(p=-1!=B[1].indexOf("&")?B[1].split("&")[0]:B[1]));0<p.length&&12E4>(new Date).getTime()-p.split(".")[1]&&(p=p.split("_"),_paq.unshift(["appendToTrackingUrl","dcmancr="+p[0]]));"use strict";
var na=/[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,ma=/[\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,U,Ha,Ya={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},X;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(y,H,T){var z;Ha=U="";if("number"===typeof T)for(z=0;z<T;z+=1)Ha+=" ";else"string"===typeof T&&(Ha=T);if((X=
H)&&"function"!==typeof H&&("object"!==typeof H||"number"!==typeof H.length))throw Error("JSON2.stringify");return u("",{"":y})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(y,H){function T(z,ba){var R,M=z[ba];if(M&&"object"===typeof M)for(R in M)if(Object.prototype.hasOwnProperty.call(M,R)){var Oa=T(M,R);void 0!==Oa?M[R]=Oa:delete M[R]}return H.call(z,ba,M)}y=String(y);na.lastIndex=0;na.test(y)&&(y=y.replace(na,function(z){return"\\u"+("0000"+z.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(y.replace(/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return y=eval("("+y+")"),"function"===typeof H?T({"":y},""):y;throw new SyntaxError("JSON2.parse");})})();"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof Piwik&&(Piwik=function(){function l(b){try{return nb(b)}catch(e){return unescape(b)}}function k(b){return"undefined"!==typeof b}function m(b){return"function"===typeof b}function u(b){return"object"===typeof b}function p(b){return"string"===typeof b||b instanceof String}function G(){var b;for(b=0;b<arguments.length;b+=1){var e=arguments[b];var g=e.shift();p(g)?Za[g].apply(Za,e):g.apply(Za,e)}}function B(b,e,g,h){if(b.addEventListener)return b.addEventListener(e,g,h),!0;if(b.attachEvent)return b.attachEvent("on"+
e,g);b["on"+e]=g}function na(b,e){var g="",h;for(h in Pa)if(Object.prototype.hasOwnProperty.call(Pa,h)){var q=Pa[h][b];m(q)&&(g+=q(e))}return g}function ma(){var b;if(!Qa)for(Qa=!0,na("load"),b=0;b<ob.length;b++)ob[b]();return!0}function U(b,e){var g=v.createElement("script");g.type="text/javascript";g.src=b;g.readyState?g.onreadystatechange=function(){var h=this.readyState;if("loaded"===h||"complete"===h)g.onreadystatechange=null,e()}:g.onload=e;v.getElementsByTagName("head")[0].appendChild(g)}function Ha(){var b=
"";try{b=w.top.document.referrer}catch(e){if(w.parent)try{b=w.parent.document.referrer}catch(g){b=""}}""===b&&(b=v.referrer);return b}function Ya(b){return(b=/^([a-z]+):/.exec(b))?b[1]:null}function X(b){var e=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(b);return e?e[1]:b}function y(b,e){return(b=(new RegExp("[\\?&#]"+e+"=([^&#]*)")).exec(b))?nb(b[1]):""}function H(b){var e=function(za,ea){return za<<ea|za>>>32-ea},g=function(za){var ea="",ua;for(ua=7;0<=ua;ua--){var Ra=za>>>4*ua&15;ea+=Ra.toString(16)}return ea},
h,q=[],Q=1732584193,N=4023233417,O=2562383102,Y=271733878,fa=3285377520,D=[];b=tc(C(b));var A=b.length;for(h=0;h<A-3;h+=4){var I=b.charCodeAt(h)<<24|b.charCodeAt(h+1)<<16|b.charCodeAt(h+2)<<8|b.charCodeAt(h+3);D.push(I)}switch(A&3){case 0:h=2147483648;break;case 1:h=b.charCodeAt(A-1)<<24|8388608;break;case 2:h=b.charCodeAt(A-2)<<24|b.charCodeAt(A-1)<<16|32768;break;case 3:h=b.charCodeAt(A-3)<<24|b.charCodeAt(A-2)<<16|b.charCodeAt(A-1)<<8|128}for(D.push(h);14!==(D.length&15);)D.push(0);D.push(A>>>
29);D.push(A<<3&4294967295);for(b=0;b<D.length;b+=16){for(h=0;16>h;h++)q[h]=D[b+h];for(h=16;79>=h;h++)q[h]=e(q[h-3]^q[h-8]^q[h-14]^q[h-16],1);I=Q;A=N;var V=O;var S=Y;var ha=fa;for(h=0;19>=h;h++){var K=e(I,5)+(A&V|~A&S)+ha+q[h]+1518500249&4294967295;ha=S;S=V;V=e(A,30);A=I;I=K}for(h=20;39>=h;h++)K=e(I,5)+(A^V^S)+ha+q[h]+1859775393&4294967295,ha=S,S=V,V=e(A,30),A=I,I=K;for(h=40;59>=h;h++)K=e(I,5)+(A&V|A&S|V&S)+ha+q[h]+2400959708&4294967295,ha=S,S=V,V=e(A,30),A=I,I=K;for(h=60;79>=h;h++)K=e(I,5)+(A^V^
S)+ha+q[h]+3395469782&4294967295,ha=S,S=V,V=e(A,30),A=I,I=K;Q=Q+I&4294967295;N=N+A&4294967295;O=O+V&4294967295;Y=Y+S&4294967295;fa=fa+ha&4294967295}K=g(Q)+g(N)+g(O)+g(Y)+g(fa);return K.toLowerCase()}function T(b,e,g){if("translate.googleusercontent.com"===b)""===g&&(g=e),e=y(e,"u"),b=X(e);else if("cc.bingj.com"===b||"webcache.googleusercontent.com"===b||"74.6."===b.slice(0,5))e=v.links[0].href,b=X(e);return[b,e,g]}function z(b){var e=b.length;"."===b.charAt(--e)&&(b=b.slice(0,e));"*."===b.slice(0,
2)&&(b=b.slice(1));return b}function ba(b){b=b&&b.text?b.text:b;if(!p(b)){var e=v.getElementsByTagName("title");e&&k(e[0])&&(b=e[0].text)}return b}function R(b){return b?!k(b.children)&&k(b.childNodes)||k(b.children)?b.children:[]:[]}function M(b,e){if(b&&b.indexOf)return b.indexOf(e);if(!k(b)||null===b||!b.length)return-1;var g=b.length;if(0===g)return-1;for(var h=0;h<g;){if(b[h]===e)return h;h++}return-1}function Oa(b){function e(h,q){if(w.getComputedStyle)return v.defaultView.getComputedStyle(h,
null)[q];if(h.currentStyle)return h.currentStyle[q]}function g(h,q,Q,N,O,Y,fa){var D=h.parentNode,A;a:{for(A=h.parentNode;A;){if(A===v){A=!0;break a}A=A.parentNode}A=!1}if(!A)return!1;if(9===D.nodeType)return!0;if("0"===e(h,"opacity")||"none"===e(h,"display")||"hidden"===e(h,"visibility"))return!1;k(q)&&k(Q)&&k(N)&&k(O)&&k(Y)&&k(fa)||(q=h.offsetTop,O=h.offsetLeft,N=q+h.offsetHeight,Q=O+h.offsetWidth,Y=h.offsetWidth,fa=h.offsetHeight);if(b===h&&(0===fa||0===Y)&&"hidden"===e(h,"overflow"))return!1;
if(D){if("hidden"===e(D,"overflow")||"scroll"===e(D,"overflow"))if(O+1>D.offsetWidth+D.scrollLeft||O+Y-1<D.scrollLeft||q+1>D.offsetHeight+D.scrollTop||q+fa-1<D.scrollTop)return!1;h.offsetParent===D&&(O+=D.offsetLeft,q+=D.offsetTop);return g(D,q,Q,N,O,Y,fa)}return!0}return b?g(b):!1}function uc(b,e){if(e)return e;"piwik.php"===b.slice(-9)&&(b=b.slice(0,b.length-9));return b}function Aa(b){var e=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(v.referrer);
if(e){if(e[1]!==String(b))return!1;w.name="Piwik_Overlay###"+e[2]+"###"+e[3]}b=w.name.split("###");return 3===b.length&&"Piwik_Overlay"===b[0]}function vc(b,e,g){var h=w.name.split("###"),q=h[1],Q=h[2],N=uc(b,e);U(N+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(N,g,q,Q)})}function Lb(b,e){function g(a,c,d,f,n,r){if(!va){if(d){var x=new Date;x.setTime(x.getTime()+d)}if(n)v.cookie=a+"="+C(c)+(d?";expires="+x.toGMTString():"")+";path="+(f||"/")+(r?";secure":"");else{var L=
document.domain;if(L.endsWith(".docomo.ne.jp"))document.domain.split("."),v.cookie=a+"="+C(c)+(d?";expires="+x.toGMTString():"")+";path="+(f||"/")+";domain=.docomo.ne.jp"+(r?";secure":"");else{var F=document.domain.split("."),J=F.length,la=!1;n="."+F[J-1];for(var Z=J-2;0<=Z;Z--){if(Z==J-2&&L.endsWith(".co.jp")||L.endsWith(".ne.jp")||L.endsWith(".or.jp")||L.endsWith(".ac.jp")||L.endsWith(".ad.jp")||L.endsWith(".ed.jp")||L.endsWith(".go.jp")||L.endsWith(".gr.jp")||L.endsWith(".lg.jp"))n="."+F[Z]+n,
Z--;n="."+F[Z]+n;v.cookie=a+"="+C(c)+(d?";expires="+x.toGMTString():"")+";path="+(f||"/")+";domain="+n+(r?";secure":"");for(var Ba=document.cookie.split(";"),ia=0;ia<Ba.length;ia++)if(Ba[ia].split("=")[0].trim()==a){la=!0;break}if(la)break}}}}}function h(a){return va?0:(a=(new RegExp("(^|;)[ ]*"+a+"=([^;]*)")).exec(v.cookie))?nb(a[2]):0}function q(a){if(Mb){var c=/#.*/;return a.replace(c,"")}return a}function Q(a){var c;for(c=0;c<$a.length;c++){var d=z($a[c].toLowerCase());if(a===d)return!0;if("."===
d.slice(0,1)){if(a===d.slice(1))return!0;var f=a.length-d.length;if(0<f&&a.slice(f)===d)return!0}}return!1}function N(a,c){c=!0;a=ja+(0>ja.indexOf("?")?"?":"&")+a;var d=Ia("daReqProb");if(null==d||0==(new Date).getTime()%d)if(null!=Ia("afterAuthFlg")&&(a+="&afterAuthFlg=1"),1==Ia("trackingType")?null!=Ia("afterAuthFlg")?(a+="&trackingType=1",(new Date).getTime(),d=pb+"_dcmsend",0===h(d)?g(d,1,4752E5,"/"):c=!1):c=!1:2==Ia("trackingType")&&(a+="&trackingType=2"),c){if(0>a.indexOf("&afterAuthFlg=1")&&
window.navigator.cookieEnabled&&document.cookie)for(c=document.cookie.split("; "),d=0;d<c.length;d++){var f=c[d].split("=");if("dcmredcook"===f[0]){a+="&afterAuthFlg=1";break}else if("dcmunioncook"===f[0]){a+="&afterAuthFlg=1";break}}c=document.createElement("img");c.setAttribute("src",a);c.style.display="none";document.body.appendChild(c)}}function O(a,c,d){k(d)&&null!==d||(d=!0);try{var f=w.XMLHttpRequest?new w.XMLHttpRequest:w.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;f.open("POST",
ja,!0);f.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!d?"function"===typeof c&&c():N(a,c)};f.setRequestHeader("Content-Type",Nb);f.send(a)}catch(n){d&&N(a,c)}}function Y(a){a=(new Date).getTime()+a;if(!Sa||a>Sa)Sa=a}function fa(a){var c=(new Date).getTime();Ja&&c<Ja?(c=Ja-c,setTimeout(a,c),Y(c+50),Ja+=50):(!1===Ja&&(Ja=c+800),a())}function D(a,c,d){!ab&&a&&fa(function(){"POST"===Ob?O(a,d):N(a,d);Y(c)})}function A(a,c){var d=ab?!1:a&&a.length;if(d){var f='{"requests":["?'+
a.join('","?')+'"]}';fa(function(){O(f,null,!1);Y(c)})}}function I(a){return pb+a+"."+P+"."+bb}function V(){if(va)return"0";if(!k(ca.cookieEnabled)){var a=I("testcookie");g(a,"1");return"1"===h(a)?"1":"0"}return ca.cookieEnabled?"1":"0"}function S(){bb=qb((Ca||rb)+(qa||"/")).slice(0,4)}function ha(){var a=I("cvar");a=h(a);return a.length&&(a=JSON2.parse(a),u(a))?a:{}}function K(){sb=(new Date).getTime()}function za(a){a||(a=32);var c=Math.round((new Date).getTime()/1E3),d=h("_pk_id"),f=h("daxtr");
if(16==a&&d)return c=d.split("."),c.unshift("0"),Da.length&&(c[1]=Da),c;if(32==a&&f)return c=f.split("."),c.unshift("0"),Da.length&&(c[1]=Da),c;a=Da.length?Da:"0"===V()?"":qb((ca.userAgent||"")+(ca.platform||"")+JSON2.stringify(ra)+(new Date).getTime()+Math.random()).slice(0,a);return c=["1",a,c,0,c,"",""]}function ea(a){a=za(a);var c=a[0],d=a[1],f=a[2]?a[2]:a[4],n=a[3]?a[3]:1,r=a[4],x="undefined"==a[5]||""==a[5]?a[4]:a[5];k(a[6])||(a[6]="");return{newVisitor:c,uuid:d,createTs:f,visitCount:n,currentVisitTs:r,
lastVisitTs:x,lastEcommerceOrderTs:a[6]}}function ua(a){if(P){(new Date).getTime();k(a)||(a=ea(16));var c=h("_pk_id."+P+"."+bb),d=h("_pk_id");c&&!d?d=c:!c&&d?c=d:(c=a.uuid+"."+a.createTs+".",d=a.uuid+"."+a.createTs+".");g("_pk_id."+P+"."+bb,c,339552E5,qa,document.domain);g("_pk_id",d,339552E5,qa)}}function Ra(a){P&&((new Date).getTime(),k(a)||(a=ea(32)),g("daxtr",a.uuid+"."+a.createTs+".",339552E5,qa))}function Ka(){var a=h(I("ref"));if(a.length)try{if(a=JSON2.parse(a),u(a))return a}catch(c){}return["",
"",0,""]}function Pb(){var a=va;va=!1;g("daxtr","",-86400,qa,Ca);var c=I("ses");g(c,"",-86400,qa,Ca);c=I("cvar");g(c,"",-86400,qa,Ca);c=I("ref");g(c,"",-86400,qa,Ca);va=a}function Qb(a){if(a&&u(a)){var c=[];for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&c.push(d);var d={};c.sort();var f=c.length,n;for(n=0;n<f;n++)d[c[n]]=a[c[n]];return d}}function oa(a,c,d,f){function n(cb,wc){cb=JSON2.stringify(cb);return 2<cb.length?"&"+wc+"="+C(cb):""}var r=new Date,x=Math.round(r.getTime()/1E3),L=da,F=
I("ses");I("ref");var J=I("cvar");var la=h(F);var Z=Ka();var Ba=db||Rb;va&&Pb();if(ab)return"";F=ea(16);var ia=ea(32);k(f)||(f="");var Ea={};var sa=location.search.substring(1).split("&");for(f=0;sa[f];f++){var ta=sa[f].split("=");Ea[ta[0]]=ta[1]}Ea.dcmancr&&(ia.uuid=Ea.dcmancr.split(".")[0]);var Ta=v.characterSet||v.charset;Ta&&"utf-8"!==Ta.toLowerCase()||(Ta=null);ta=Z[0];var Ua=Z[1];Ea=Z[2];sa=Z[3];if(!la){la=tb/1E3;if(!F.lastVisitTs||x-F.lastVisitTs>la)F.visitCount++,F.lastVisitTs=F.currentVisitTs;
if(!ia.lastVisitTs||x-ia.lastVisitTs>la)ia.visitCount++,ia.lastVisitTs=ia.currentVisitTs;if(!ub||!ta.length){for(f in eb)if(Object.prototype.hasOwnProperty.call(eb,f)&&(ta=y(Ba,eb[f]),ta.length))break;for(f in fb)if(Object.prototype.hasOwnProperty.call(fb,f)&&(Ua=y(Ba,fb[f]),Ua.length))break}la=X(Fa);Z=sa.length?X(sa):"";!la.length||Q(la)||ub&&Z.length&&!Q(Z)||(sa=Fa);if(sa.length||ta.length)Ea=x,Z=[ta,Ua,Ea,q(sa.slice(0,1024))]}x=!1;1===Ia("trackingType")&&(x=!0);if(x)a="idsite="+P+"&url="+C(q(Ba))+
(Fa.length?"&urlref="+C(q(Fa)):"")+"&_id="+F.uuid+"&_id2="+ia.uuid;else{a+="&idsite="+P+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+r.getHours()+"&m="+r.getMinutes()+"&s="+r.getSeconds()+"&url="+C(q(Ba))+(Fa.length?"&urlref="+C(q(Fa)):"")+(La&&La.length?"&uid="+C(La):"")+"&_id="+F.uuid+"&_idts="+F.createTs+"&_idvc="+F.visitCount+"&_id2="+ia.uuid+"&_idn="+F.newVisitor+(ta.length?"&_rcn="+C(ta):"")+(Ua.length?"&_rck="+C(Ua):"")+"&_refts="+Ea+"&_viewts="+F.lastVisitTs+(String(F.lastEcommerceOrderTs).length?
"&_ects="+F.lastEcommerceOrderTs:"")+(String(sa).length?"&_ref="+C(q(sa.slice(0,1024))):"")+(Ta?"&cs="+C(Ta):"")+"&send_image=0";for(f in ra)Object.prototype.hasOwnProperty.call(ra,f)&&(a+="&"+f+"="+ra[f]);c?a+="&data="+C(JSON2.stringify(c)):wa&&(a+="&data="+C(JSON2.stringify(wa)));c=Qb(Ga);r=Qb(vb);a+=n(c,"cvar");a+=n(r,"e_cvar");if(da){a+=n(da,"_cvar");for(f in L)Object.prototype.hasOwnProperty.call(L,f)&&(""===da[f][0]||""===da[f][1])&&delete da[f];Sb&&g(J,JSON2.stringify(da),tb,qa,Ca)}Tb&&(wb?
a+="&gt_ms="+wb:Ma&&Ma.timing&&Ma.timing.requestStart&&Ma.timing.responseEnd&&(a+="&gt_ms="+(Ma.timing.responseEnd-Ma.timing.requestStart)))}ua(F);Ra(ia);a+=na(d);xb.length&&(a+="&"+xb);m(yb)&&(a=yb(a));if(window.navigator.cookieEnabled&&document.cookie)for(d=document.cookie.split("; "),f=0;f<d.length;f++)d[f].split("=")[0].split(".");return a}function Ub(a,c,d,f,n,r){var x="idgoal=0",L=new Date,F=[],J;if(String(a).length){x+="&ec_id="+C(a);var la=Math.round(L.getTime()/1E3)}x+="&revenue="+c;String(d).length&&
(x+="&ec_st="+d);String(f).length&&(x+="&ec_tx="+f);String(n).length&&(x+="&ec_sh="+n);String(r).length&&(x+="&ec_dt="+r);if(aa){for(J in aa)Object.prototype.hasOwnProperty.call(aa,J)&&(k(aa[J][1])||(aa[J][1]=""),k(aa[J][2])||(aa[J][2]=""),k(aa[J][3])&&0!==String(aa[J][3]).length||(aa[J][3]=0),k(aa[J][4])&&0!==String(aa[J][4]).length||(aa[J][4]=1),F.push(aa[J]));x+="&ec_items="+C(JSON2.stringify(F))}x=oa(x,wa,"ecommerce",la);D(x,W)}function xc(a,c){var d=new Date;a=oa("action_name="+C(ba(a||Vb)),
c,"log");D(a,W);zb&&Va&&!Wb&&(Wb=!0,B(v,"click",K),B(v,"mouseup",K),B(v,"mousedown",K),B(v,"mousemove",K),B(v,"mousewheel",K),B(w,"DOMMouseScroll",K),B(w,"scroll",K),B(v,"keypress",K),B(v,"keydown",K),B(v,"keyup",K),B(w,"resize",K),B(w,"focus",K),B(w,"blur",K),sb=d.getTime(),setTimeout(function n(){d=new Date;if(sb+Va>d.getTime()){if(zb<d.getTime()){var r=oa("ping=1",c,"ping");D(r,W)}setTimeout(n,Va)}},Va))}function Ab(a,c){var d="(^| )(piwik[_-]"+c;if(a)for(c=0;c<a.length;c++)d+="|"+a[c];return new RegExp(d+
")( |$)")}function Wa(a){return ja&&a&&0===String(a).indexOf(ja)}function Bb(a){var c=a,d;for(d=c.parentNode;null!==d&&k(d)&&!t.isLinkElement(c);)c=d,d=c.parentNode;a=c;if(t.hasNodeAttribute(a,"href")&&k(a.href)&&(c=t.getAttributeValueFromNode(a,"href"),!Wa(c))){c=a.hostname||X(a.href);var f=c.toLowerCase();c=a.href.replace(c,f);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(c)){d=a.className;f=Q(f);a=t.hasNodeAttribute(a,"download");if(Wa(c))d=0;else{var n=Ab(Xb,"download"),
r=Ab(Yb,"link"),x=new RegExp("\\.("+xa.join("|")+")([?&#]|$)","i");d=r.test(d)?"link":a||n.test(d)||x.test(c)?"download":f?0:"link"}if(d)return{type:d,href:c}}}}function Xa(a,c,d,f){if(a=E.buildInteractionRequestParams(a,c,d,f))return oa(a,null,"contentInteraction")}function Zb(a,c,d,f,n){if(k(a)){if(Wa(a))return a;var r=E.toAbsoluteUrl(a);r="redirecturl="+C(r)+"&";r+=Xa(c,d,f,n||a);a="&";0>ja.indexOf("?")&&(a="?");return ja+a+r}}function Cb(a,c){if(!a||!c)return!1;var d=E.findTargetNode(a);if(E.shouldIgnoreInteraction(d))return!1;
if(a=d=E.findTargetNodeNoDefault(a))a=!(d&&c&&(d.contains?d.contains(c):d===c||d.compareDocumentPosition&&d.compareDocumentPosition(c)&16));return a?!1:!0}function $b(a,c,d){if(a){var f=E.findParentContentNode(a);if(f&&Cb(f,a)&&(a=E.buildContentBlock(f)))return!a.target&&d&&(a.target=d),E.buildInteractionRequestParams(c,a.name,a.piece,a.target)}}function ac(a){if(!ya||!ya.length)return!1;var c,d;for(c=0;c<ya.length;c++)if((d=ya[c])&&d.name===a.name&&d.piece===a.piece&&d.target===a.target)return!0;
return!1}function Db(a){if(!a)return!1;var c=E.findTargetNode(a);if(!c||E.shouldIgnoreInteraction(c))return!1;var d=Bb(c);if(Eb&&d&&d.type)return!1;if(t.isLinkElement(c)&&t.hasNodeAttributeWithValue(c,"href")){d=String(t.getAttributeValueFromNode(c,"href"));if(0===d.indexOf("#"))return!1;if(Wa(d))return!0;if(!E.isUrlToCurrentDomain(d))return!1;var f=E.buildContentBlock(a);if(!f)return;a=f.name;var n=f.piece;f=f.target;if(!t.hasNodeAttributeWithValue(c,E.CONTENT_TARGET_ATTR)||c.wasContentTargetAttrReplaced)c.wasContentTargetAttrReplaced=
!0,f=E.toAbsoluteUrl(d),t.setAnyAttribute(c,E.CONTENT_TARGET_ATTR,f);d=Zb(d,"click",a,n,f);E.setHrefAttribute(c,d);return!0}return!1}function bc(a){return function(c){if(a){var d=E.findParentContentNode(a),f;c&&(f=c.target||c.srcElement);f||(f=a);if(Cb(d,f)){Y(W);t.isLinkElement(a)&&t.hasNodeAttributeWithValue(a,"href")&&t.hasNodeAttributeWithValue(a,E.CONTENT_TARGET_ATTR)&&(c=t.getAttributeValueFromNode(a,"href"),!Wa(c)&&a.wasContentTargetAttrReplaced&&t.setAnyAttribute(a,E.CONTENT_TARGET_ATTR,""));
c=Bb(a);if(gb&&c&&c.type)return c.type;if(Db(d))return"href";if(d=E.buildContentBlock(d))return d=Xa("click",d.name,d.piece,d.target),D(d,W),d}}}}function cc(a){if(a&&a.length){var c,d;for(c=0;c<a.length;c++)(d=E.findTargetNode(a[c]))&&!d.contentInteractionTrackingSetupDone&&(d.contentInteractionTrackingSetupDone=!0,B(d,"click",bc(d)))}}function dc(a,c){if(!a||!a.length)return[];var d;for(d=0;d<a.length;d++)ac(a[d])?(a.splice(d,1),d--):ya.push(a[d]);if(!a||!a.length)return[];if(c&&c.length)for(d=
0;d<c.length;d++)Db(c[d]);cc(c);var f=[];for(d=0;d<a.length;d++)c=oa(E.buildImpressionRequestParams(a[d].name,a[d].piece,a[d].target),void 0,"contentImpressions"),f.push(c);return f}function hb(a){var c=E.collectContent(a);return dc(c,a)}function Fb(a){if(!a||!a.length)return[];var c;for(c=0;c<a.length;c++)E.isNodeVisible(a[c])||(a.splice(c,1),c--);return a&&a.length?hb(a):[]}function ec(a,c,d){a=E.buildImpressionRequestParams(a,c,d);return oa(a,null,"contentImpression")}function fc(a,c){if(a&&(a=
E.findParentContentNode(a),a=E.buildContentBlock(a)))return c||(c="Unknown"),Xa(c,a.name,a.piece,a.target)}function gc(a,c,d,f,n){if(0===String(a).length||0===String(c).length)return!1;a="e_c="+C(a)+"&e_a="+C(c)+(k(d)?"&e_n="+C(d):"")+(k(f)?"&e_v="+C(f):"");n=oa(a,n,"event");D(n,W)}function hc(a,c,d,f,n){c=c+"="+C(q(a));(a=$b(n,"click",a))&&(c+="&"+a);d=oa(c,d,"link");D(d,f?0:W,f)}function ic(a,c){return""!==a?a+c.charAt(0).toUpperCase()+c.slice(1):c}function ka(a){var c,d,f=["","webkit","ms","moz"];
if(!jc)for(d=0;d<f.length;d++){var n=f[d];if(Object.prototype.hasOwnProperty.call(v,ic(n,"hidden"))){"prerender"===v[ic(n,"visibilityState")]&&(c=!0);break}}c?B(v,n+"visibilitychange",function x(){v.removeEventListener(n+"visibilitychange",x,!1);a()}):a()}function ib(a){"complete"===v.readyState?a():w.addEventListener?w.addEventListener("load",a):w.attachEvent&&w.attachEvent("onLoad",a)}function Gb(a){(v.attachEvent?"complete"===v.readyState:"loading"!==v.readyState)?a():v.addEventListener?v.addEventListener("DOMContentLoaded",
a):v.attachEvent&&v.attachEvent("onreadystatechange",a)}function kc(a){var c=Bb(a);c&&c.type&&(c.href=l(c.href),hc(c.href,c.type,void 0,null,a))}function Hb(a){a=a||w.event;var c=a.which||a.button;var d=a.target||a.srcElement;"click"===a.type?d&&kc(d):"mousedown"===a.type?1!==c&&2!==c||!d?jb=kb=null:(jb=c,kb=d):"mouseup"===a.type&&(c===jb&&d===kb&&kc(d),jb=kb=null)}function lc(a,c){c?(B(a,"mouseup",Hb,!1),B(a,"mousedown",Hb,!1)):B(a,"click",Hb,!1)}function mc(a){if(!gb){gb=!0;var c,d=Ab(nc,"ignore"),
f=v.links;if(f)for(c=0;c<f.length;c++)d.test(f[c].className)||lc(f[c],a)}}function oc(a,c,d){function f(){n=!0}if(Na)return!0;Na=!0;var n=!1,r,x;ib(function(){function L(J){setTimeout(function(){Na&&(n=!1,d.trackVisibleContentImpressions(),L(J))},J)}function F(J){setTimeout(function(){Na&&(n&&(n=!1,d.trackVisibleContentImpressions()),F(J))},J)}if(a){r=["scroll","resize"];for(x=0;x<r.length;x++)v.addEventListener?v.addEventListener(r[x],f):w.attachEvent("on"+r[x],f);F(100)}c&&0<c&&(c=parseInt(c,10),
L(c))})}function Ia(a){if("undefined"!=typeof _paq&&null!=_paq&&0<_paq.length){var c=null;_paq.forEach(function(d){d[0]===a&&(c=2==d.length?d[1]:d[0])});return c}return null}var lb={},Ib=T(v.domain,w.location.href,Ha()),rb=z(Ib[0]),Rb=l(Ib[1]),Fa=l(Ib[2]),pc=!1,Ob="GET",Nb="application/x-www-form-urlencoded; charset=UTF-8",ja=b||"",qc="",xb="",P=e||"",La="",Da="",db,Vb=v.title,xa="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),
$a=[rb],nc=[],Xb=[],Yb=[],W=500,zb,Va,Mb,wa,eb=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],fb=["pk_kwd","piwik_kwd","utm_term"],pb="_pk_",Ca,qa,va=!1,ab,jc,ub,Jb=339552E5,tb=18E5,Tb=!0,wb=0,Sb=!1,da=!1,yb,Ga={},vb={},aa={},ra={},ya=[],Na=!1,Ja=!1,gb=!1,Eb=!1,Wb=!1,sb,jb,kb,qb=H,bb;(function(){var a,c={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",
java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},d=/Mac OS X.*Safari\//.test(ca.userAgent)?w.devicePixelRatio||1:1;if(!/MSIE/.test(ca.userAgent)){if(ca.mimeTypes&&ca.mimeTypes.length)for(a in c)if(Object.prototype.hasOwnProperty.call(c,a)){var f=ca.mimeTypes[c[a]];ra[a]=f&&f.enabledPlugin?"1":"0"}"unknown"!==typeof navigator.javaEnabled&&k(ca.javaEnabled)&&ca.javaEnabled()&&(ra.java="1");m(w.GearsFactory)&&(ra.gears="1");ra.cookie=V()}ra.res=rc.width*
d+"x"+rc.height*d})();S();ua();Ra();na("run",function(a,c){var d=null;if(p(a)&&!k(lb[a])&&c){if(u(c))d=c;else if(p(c))try{eval("hookObj ="+c)}catch(f){}lb[a]=d}return d});return{hook:lb,getHook:function(a){return lb[a]},getQuery:function(){return t},getContent:function(){return E},buildContentImpressionRequest:ec,buildContentInteractionRequest:Xa,buildContentInteractionRequestNode:fc,buildContentInteractionTrackingRedirectUrl:Zb,getContentImpressionsRequestsFromNodes:hb,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:Fb,
trackCallbackOnLoad:ib,trackCallbackOnReady:Gb,buildContentImpressionsRequests:dc,wasContentImpressionAlreadyTracked:ac,appendContentInteractionToRequestIfPossible:$b,setupInteractionsTracking:cc,trackContentImpressionClickInteraction:bc,internalIsNodeVisible:Oa,isNodeAuthorizedToTriggerInteraction:Cb,replaceHrefIfInternalLink:Db,getConfigDownloadExtensions:function(){return xa},enableTrackOnlyVisibleContent:function(a,c){return oc(a,c,this)},clearTrackedContentImpressions:function(){ya=[]},getTrackedContentImpressions:function(){return ya},
clearEnableTrackOnlyVisibleContent:function(){Na=!1},disableLinkTracking:function(){Eb=gb=!1},getConfigVisitorCookieTimeout:function(){return Jb},getRemainingVisitorCookieTimeout:function(){var a=(new Date).getTime(),c=ea().createTs;return 1E3*parseInt(c,10)+Jb-a},afterAuthFlg:function(a){if(1===a&&window.navigator.cookieEnabled){(new Date).getTime();a=0;if(document.cookie)for(var c=document.cookie.split("; "),d=0;d<c.length;d++)if("dcmunioncook"===c[d].split("=")[0]){a=1;break}0===a&&g("dcmunioncook",
"1",36E5,"/")}},trackingType:function(a){if((1==a||2==a)&&"function"===typeof dcmganCallback){a=dcmganCallback;var c={};c.uid=ea().uuid;a(c)}},daReqProb:function(a){},gaCallbackTimeout:function(a){clearTimeout(a)},getVisitorId:function(){return ea().uuid},getVisitorInfo:function(){return za()},getAttributionInfo:function(){return Ka()},getAttributionCampaignName:function(){return Ka()[0]},getAttributionCampaignKeyword:function(){return Ka()[1]},getAttributionReferrerTimestamp:function(){return Ka()[2]},
getAttributionReferrerUrl:function(){return Ka()[3]},setTrackerUrl:function(a){ja=a},getTrackerUrl:function(){return ja},getSiteId:function(){return P},setSiteId:function(a){P=a;ua();Ra()},setUserId:function(a){k(a)&&a.length&&(La=a,Da=qb(La).substr(0,32))},getUserId:function(){return La},setCustomData:function(a,c){u(a)?wa=a:(wa||(wa={}),wa[a]=c)},getCustomData:function(){return wa},setCustomRequestProcessing:function(a){yb=a},appendToTrackingUrl:function(a){xb=a},getRequest:function(a){return oa(a)},
addPlugin:function(a,c){Pa[a]=c},setCustomVariable:function(a,c,d,f){k(f)||(f="visit");k(c)&&(k(d)||(d=""),0<a&&(c=p(c)?c:String(c),d=p(d)?d:String(d),c=[c.slice(0,200),d.slice(0,200)],"visit"===f||2===f?(!1===da&&(da=ha()),da[a]=c):"page"===f||3===f?Ga[a]=c:"event"===f&&(vb[a]=c)))},getCustomVariable:function(a,c){k(c)||(c="visit");if("page"===c||3===c)var d=Ga[a];else if("event"===c)d=vb[a];else if("visit"===c||2===c)!1===da&&(da=ha()),d=da[a];return!k(d)||d&&""===d[0]?!1:d},deleteCustomVariable:function(a,
c){this.getCustomVariable(a,c)&&this.setCustomVariable(a,"","",c)},storeCustomVariablesInCookie:function(){Sb=!0},setLinkTrackingTimer:function(a){W=a},setDownloadExtensions:function(a){p(a)&&(a=a.split("|"));xa=a},addDownloadExtensions:function(a){var c;p(a)&&(a=a.split("|"));for(c=0;c<a.length;c++)xa.push(a[c])},removeDownloadExtensions:function(a){var c,d=[];p(a)&&(a=a.split("|"));for(c=0;c<xa.length;c++)-1===M(a,xa[c])&&d.push(xa[c]);xa=d},setDomains:function(a){$a=p(a)?[a]:a;$a.push(rb)},setIgnoreClasses:function(a){nc=
p(a)?[a]:a},setRequestMethod:function(a){Ob=a||"GET"},setRequestContentType:function(a){Nb=a||"application/x-www-form-urlencoded; charset=UTF-8"},setReferrerUrl:function(a){Fa=a},setCustomUrl:function(a){var c=Rb;if(Ya(a))db=a;else if("/"===a.slice(0,1))db=Ya(c)+"://"+X(c)+a;else{c=q(c);var d=c.indexOf("?");0<=d&&(c=c.slice(0,d));d=c.lastIndexOf("/");d!==c.length-1&&(c=c.slice(0,d+1));db=c+a}},setDocumentTitle:function(a){Vb=a},setAPIUrl:function(a){qc=a},setDownloadClasses:function(a){Xb=p(a)?[a]:
a},setLinkClasses:function(a){Yb=p(a)?[a]:a},setCampaignNameKey:function(a){eb=p(a)?[a]:a},setCampaignKeywordKey:function(a){fb=p(a)?[a]:a},discardHashTag:function(a){Mb=a},setCookieNamePrefix:function(a){pb=a;da=ha()},setCookieDomain:function(a){a=z(a);g("test","testvalue",1E4,null,a);if("testvalue"===h("test")){g("test","",-86400,null,a);var c=!0}else c=!1;c&&(Ca=a,S())},setCookiePath:function(a){qa=a;S()},setVisitorCookieTimeout:function(a){Jb=1E3*a},setSessionCookieTimeout:function(a){tb=1E3*
a},setReferralCookieTimeout:function(a){},setConversionAttributionFirstReferrer:function(a){ub=a},disableCookies:function(){va=!0;ra.cookie="0"},deleteCookies:function(){Pb()},setDoNotTrack:function(a){var c=ca.doNotTrack||ca.msDoNotTrack;(ab=a&&("yes"===c||"1"===c))&&this.disableCookies()},addListener:function(a,c){lc(a,c)},enableLinkTracking:function(a){Eb=!0;Qa?mc(a):ob.push(function(){mc(a)})},enableJSErrorTracking:function(){if(!pc){pc=!0;var a=w.onerror;w.onerror=function(c,d,f,n,r){ka(function(){var x=
d+":"+f;n&&(x+=":"+n);gc("JavaScript Errors",x,c)});return a?a(c,d,f,n,r):!1}}},disablePerformanceTracking:function(){Tb=!1},setGenerationTimeMs:function(a){wb=parseInt(a,10)},setHeartBeatTimer:function(a,c){zb=(new Date).getTime()+1E3*a;Va=1E3*c},killFrame:function(){w.location!==w.top.location&&(w.top.location=w.location)},redirectFile:function(a){"file:"===w.location.protocol&&(w.location=a)},setCountPreRendered:function(a){jc=a},trackGoal:function(a,c,d){ka(function(){var f=oa("idgoal="+a+(c?
"&revenue="+c:""),d,"goal");D(f,W)})},trackLink:function(a,c,d,f){ka(function(){hc(a,c,d,f)})},trackPageView:function(a,c){ya=[];Aa(P)?ka(function(){vc(ja,qc,P)}):ka(function(){xc(a,c)})},trackAllContentImpressions:function(){Aa(P)||ka(function(){Gb(function(){var a=E.findContentNodes();a=hb(a);A(a,W)})})},trackVisibleContentImpressions:function(a,c){Aa(P)||(k(a)||(a=!0),k(c)||(c=750),oc(a,c,this),ka(function(){ib(function(){var d=E.findContentNodes();d=Fb(d);A(d,W)})}))},trackContentImpression:function(a,
c,d){!Aa(P)&&a&&(c=c||"Unknown",ka(function(){var f=ec(a,c,d);D(f,W)}))},trackContentImpressionsWithinNode:function(a){!Aa(P)&&a&&ka(function(){Na?ib(function(){var c=E.findContentNodesWithinNode(a);c=Fb(c);A(c,W)}):Gb(function(){var c=E.findContentNodesWithinNode(a);c=hb(c);A(c,W)})})},trackContentInteraction:function(a,c,d,f){!Aa(P)&&a&&c&&(d=d||"Unknown",ka(function(){var n=Xa(a,c,d,f);D(n,W)}))},trackContentInteractionNode:function(a,c){!Aa(P)&&a&&ka(function(){var d=fc(a,c);D(d,W)})},trackEvent:function(a,
c,d,f){ka(function(){gc(a,c,d,f)})},trackSiteSearch:function(a,c,d){ka(function(){var f=oa("search="+C(a)+(c?"&search_cat="+C(c):"")+(k(d)?"&search_count="+d:""),void 0,"sitesearch");D(f,W)})},setEcommerceView:function(a,c,d,f){k(d)&&d.length?d instanceof Array&&(d=JSON2.stringify(d)):d="";Ga[5]=["_pkc",d];k(f)&&String(f).length&&(Ga[2]=["_pkp",f]);if(k(a)&&a.length||k(c)&&c.length)k(a)&&a.length&&(Ga[3]=["_pks",a]),k(c)&&c.length||(c=""),Ga[4]=["_pkn",c]},addEcommerceItem:function(a,c,d,f,n){a.length&&
(aa[a]=[a,c,d,f,n])},trackEcommerceOrder:function(a,c,d,f,n,r){String(a).length&&k(c)&&Ub(a,c,d,f,n,r)},trackEcommerceCartUpdate:function(a){k(a)&&Ub("",a,"","","","")},diPiNK:function(a){if(window.navigator.cookieEnabled&&1!=h("dcmdipink")&&(null==a||0==(new Date).getTime()%a)){var c=h("_pk_id");if(c){c=c.split(".")[0];var d=document.createElement("img");d.style.display="none";a="https:"==document.location.protocol?"https://":"http://";d.src=a+"sync.im-apps.net/imid/set?cid=6094&tid=did&uid="+c;
document.body.appendChild(d);c=document.createElement("iframe");a="https:"==document.location.protocol?"https://":"http://";c.src=a+"cf.im-apps.net/imid/beacon.html";c.style.display="none";document.body.appendChild(c);a=(new Date).getTime();a=(new Date(a+864E5)).toGMTString();a="dcmdipink="+escape(1)+"; expires="+a+"; path=/";document.cookie=a}}},diPiNK2:function(a){if(1!=h("dcmdipink")){var c=[];if(""!=document.cookie){a=document.cookie.split("; ");for(var d=0;d<a.length;d++){var f=a[d].split("=");
c[f[0]]=decodeURIComponent(f[1])}}d=document;a=d.createElement("script");d=d.getElementsByTagName("script")[0];a.async=!0;a.src="https://dmp.im-apps.net/scripts/im-uid-hook.js?cid=6094";d.parentNode.insertBefore(a,d);if(""!=document.cookie)for(a=document.cookie.split("; "),d=0;d<a.length;d++)f=a[d].split("="),c[f[0]]=decodeURIComponent(f[1]);setTimeout(function(){if(""!=document.cookie)for(var n=document.cookie.split("; "),r=0;r<n.length;r++){var x=n[r].split("=");c[x[0]]=decodeURIComponent(x[1])}n=
h("daxtr");r=c["_im_uid.6094"];n&&r&&(n=n.split(".")[0],n="https://b6.im-apps.net/6094/map/"+r+"/"+n,r=document.createElement("img"),r.src=n,r.style.display="none",r.style.width="1px",r.style.height="1px",document.body.appendChild(r),n=(new Date).getTime(),n=(new Date(n+864E5)).toGMTString(),n="dcmdipink="+escape(1)+"; expires="+n+"; path=/",document.cookie=n)},500)}},dcmsyfl:function(a){},dcmsydc:function(a){if(window.navigator.cookieEnabled&&!(1==h("dcmsydc")||null==a||0>=a||0!=(new Date).getTime()%
a)&&(a=h("daxtr"))){a=a.split(".")[0];a="&idsite="+P+"&url="+(document.location.protocol+"//"+document.domain)+"&dauid="+a;var c=document.createElement("img");c.setAttribute("src","//cm.g.doubleclick.net/pixel?google_nid=dmc_dmp&google_cm&google_sc"+a);c.style.display="none";document.body.appendChild(c);g("dcmsydc","1",4752E5,"/")}},dcmsyal:function(a){},dcmsyhk:function(a){if(window.navigator.cookieEnabled&&!(1==h("dcmsyhk")||null==a||0>=a||0!=(new Date).getTime()%a)&&(a=h("daxtr"))){a=a.split(".")[0];
var c=-1<ja.indexOf("dmc-t")?"//sy.dcm-analytics.com":"//sy.docomo-analytics.com";a="?oid=207d81ffda0cc019&rdr="+C(c+"/dcm/sy/hk/?idsite="+(P+"&url="+(document.location.protocol+"//"+document.domain)+"&dauid="+a+"&uid={AONEID}"));c=document.createElement("img");c.setAttribute("src","//aw.dw.impact-ad.jp/c/u/"+a);c.style.display="none";document.body.appendChild(c);g("dcmsyhk","1",2592E6,"/")}},dcmsytd:function(a){},dcmsyyh:function(a){},dcmsyde:function(a){if(window.navigator.cookieEnabled&&!(1==h("dcmsyde")||
null==a||0>=a||0!=(new Date).getTime()%a)&&(a=h("daxtr"))){a=a.split(".")[0];var c="idsite="+P,d="url="+C(document.location.protocol+"//"+document.domain);a="?p_id=docomo&"+c+"&"+d+"&dauid="+a+"&companyid=11";c=document.createElement("img");c.setAttribute("src","//pp.d2-apps.net/v1/redirect"+a);c.style.display="none";document.body.appendChild(c);g("dcmsyde","1",864E5,"/")}},cvv:function(a){var c=(-1<ja.indexOf("dmc-t.docomo.ne.jp")?"//devcv.dmc-t.docomo.ne.jp":"//cv.dmc.docomo.ne.jp")+"/dcm/coll/cv/";
h("daxtr")&&(a+="&dauid="+h("daxtr").split(".")[0]);var d=document.createElement("img");d.setAttribute("src",c+(-1<a.indexOf("?")?a:"?"+a));d.style.display="none";document.body.appendChild(d)},cvc:function(a,c){var d=(-1<ja.indexOf("dmc-t.docomo.ne.jp")?"//devcv.dmc-t.docomo.ne.jp":"//cv.dmc.docomo.ne.jp")+"/dcm/coll/cv/",f=document.getElementById(a);if(f){h("daxtr")&&(c+="&dauid="+h("daxtr").split(".")[0]);var n=f.href;f.onclick=function(r){c=c.replace(/&dcm_z=[0-9]{13}/,"");c+="&dcm_z="+(new Date).getTime();
var x=new XMLHttpRequest,L=r.button;r.which||void 0===L||(r.which=L&1?1:L&2?3:L&4?2:0);if(!(0!==r.button&&1!==r.which||r.altKey||r.ctrlKey||r.shiftKey||r.metaKey||"_blank"==f.target||"_new"==f.target)){r.preventDefault();x.onreadystatechange=function(){2==x.readyState&&(null!=F&&(clearTimeout(F),F=null),window.location.href=n)};var F=setTimeout(function(){window.location.href=n},1E3)}x.open("GET",d+(-1<c.indexOf("?")?c:"?"+c));x.withCredentials=!0;x.send()}}}}}var Sa,Pa={},v=document,ca=navigator,
rc=screen,w=window,Ma=w.performance||w.mozPerformance||w.msPerformance||w.webkitPerformance,Qa=!1,ob=[],C=w.encodeURIComponent,nb=w.decodeURIComponent,tc=unescape,pa,t={htmlCollectionToArray:function(b){var e=[],g;if(!b||!b.length)return e;for(g=0;g<b.length;g++)e.push(b[g]);return e},find:function(b){if(!document.querySelectorAll||!b)return[];b=document.querySelectorAll(b);return this.htmlCollectionToArray(b)},findMultiple:function(b){if(!b||!b.length)return[];var e,g=[];for(e=0;e<b.length;e++){var h=
this.find(b[e]);g=g.concat(h)}return g=this.makeNodesUnique(g)},findNodesByTagName:function(b,e){if(!b||!e||!b.getElementsByTagName)return[];b=b.getElementsByTagName(e);return this.htmlCollectionToArray(b)},makeNodesUnique:function(b){var e=[].concat(b);b.sort(function(N,O){if(N===O)return 0;N=M(e,N);O=M(e,O);return N===O?0:N>O?-1:1});if(1>=b.length)return b;var g=0,h=0,q=[],Q;for(Q=b[g++];Q;)Q===b[g]&&(h=q.push(g)),Q=b[g++]||null;for(;h--;)b.splice(q[h],1);return b},getAttributeValueFromNode:function(b,
e){if(this.hasNodeAttribute(b,e)){if(b&&b.getAttribute)return b.getAttribute(e);if(b&&b.attributes&&"undefined"!==typeof b.attributes[e]){if(b.attributes[e].value)return b.attributes[e].value;if(b.attributes[e].nodeValue)return b.attributes[e].nodeValue;var g=b.attributes;if(g){for(b=0;b<g.length;b++)if(g[b].nodeName===e)return g[b].nodeValue;return null}}}},hasNodeAttributeWithValue:function(b,e){return!!this.getAttributeValueFromNode(b,e)},hasNodeAttribute:function(b,e){return b&&b.hasAttribute?
b.hasAttribute(e):b&&b.attributes?"undefined"!==typeof b.attributes[e]:!1},hasNodeCssClass:function(b,e){return b&&e&&b.className&&(b=b.className.split(" "),-1!==M(b,e))?!0:!1},findNodesHavingAttribute:function(b,e,g){g||(g=[]);if(!b||!e)return g;b=R(b);if(!b||!b.length)return g;var h;for(h=0;h<b.length;h++){var q=b[h];this.hasNodeAttribute(q,e)&&g.push(q);g=this.findNodesHavingAttribute(q,e,g)}return g},findFirstNodeHavingAttribute:function(b,e){if(b&&e){if(this.hasNodeAttribute(b,e))return b;if((b=
this.findNodesHavingAttribute(b,e))&&b.length)return b[0]}},findFirstNodeHavingAttributeWithValue:function(b,e){if(b&&e){if(this.hasNodeAttributeWithValue(b,e))return b;if((b=this.findNodesHavingAttribute(b,e))&&b.length){var g;for(g=0;g<b.length;g++)if(this.getAttributeValueFromNode(b[g],e))return b[g]}}},findNodesHavingCssClass:function(b,e,g){g||(g=[]);if(!b||!e)return g;if(b.getElementsByClassName)return e=b.getElementsByClassName(e),this.htmlCollectionToArray(e);b=R(b);if(!b||!b.length)return[];
var h;for(h=0;h<b.length;h++){var q=b[h];this.hasNodeCssClass(q,e)&&g.push(q);g=this.findNodesHavingCssClass(q,e,g)}return g},findFirstNodeHavingClass:function(b,e){if(b&&e){if(this.hasNodeCssClass(b,e))return b;if((b=this.findNodesHavingCssClass(b,e))&&b.length)return b[0]}},isLinkElement:function(b){if(!b)return!1;b=String(b.nodeName).toLowerCase();return-1!==M(["a","area"],b)},setAnyAttribute:function(b,e,g){b&&e&&(b.setAttribute?b.setAttribute(e,g):b[e]=g)}},E={CONTENT_ATTR:"data-track-content",
CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return t.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(b){if(!b)return[];
var e=t.findNodesHavingCssClass(b,this.CONTENT_CLASS),g=t.findNodesHavingAttribute(b,this.CONTENT_ATTR);if(g&&g.length){var h;for(h=0;h<g.length;h++)e.push(g[h])}t.hasNodeAttribute(b,this.CONTENT_ATTR)?e.push(b):t.hasNodeCssClass(b,this.CONTENT_CLASS)&&e.push(b);return e=t.makeNodesUnique(e)},findParentContentNode:function(b){if(b)for(var e=0;b&&b!==v&&b.parentNode;){if(t.hasNodeAttribute(b,this.CONTENT_ATTR)||t.hasNodeCssClass(b,this.CONTENT_CLASS))return b;b=b.parentNode;if(1E3<e)break;e++}},findPieceNode:function(b){var e;
(e=t.findFirstNodeHavingAttribute(b,this.CONTENT_PIECE_ATTR))||(e=t.findFirstNodeHavingClass(b,this.CONTENT_PIECE_CLASS));return e?e:b},findTargetNodeNoDefault:function(b){if(b){var e=t.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_TARGET_ATTR);if(e||(e=t.findFirstNodeHavingAttribute(b,this.CONTENT_TARGET_ATTR))||(e=t.findFirstNodeHavingClass(b,this.CONTENT_TARGET_CLASS)))return e}},findTargetNode:function(b){var e=this.findTargetNodeNoDefault(b);return e?e:b},findContentName:function(b){if(b){var e=
t.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_NAME_ATTR);if(e)return t.getAttributeValueFromNode(e,this.CONTENT_NAME_ATTR);if(e=this.findContentPiece(b))return this.removeDomainIfIsInLink(e);if(t.hasNodeAttributeWithValue(b,"title"))return t.getAttributeValueFromNode(b,"title");e=this.findPieceNode(b);if(t.hasNodeAttributeWithValue(e,"title"))return t.getAttributeValueFromNode(e,"title");b=this.findTargetNode(b);if(t.hasNodeAttributeWithValue(b,"title"))return t.getAttributeValueFromNode(b,
"title")}},findContentPiece:function(b){if(b){var e=t.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_PIECE_ATTR);if(e)return t.getAttributeValueFromNode(e,this.CONTENT_PIECE_ATTR);b=this.findPieceNode(b);if(b=this.findMediaUrlInNode(b))return this.toAbsoluteUrl(b)}},findContentTarget:function(b){if(b){var e=this.findTargetNode(b);if(t.hasNodeAttributeWithValue(e,this.CONTENT_TARGET_ATTR))return t.getAttributeValueFromNode(e,this.CONTENT_TARGET_ATTR);if(t.hasNodeAttributeWithValue(e,"href"))return b=
t.getAttributeValueFromNode(e,"href"),this.toAbsoluteUrl(b);b=this.findPieceNode(b);if(t.hasNodeAttributeWithValue(b,"href"))return b=t.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(b)}},isSameDomain:function(b){if(!b||!b.indexOf)return!1;if(0===b.indexOf(this.getLocation().origin))return!0;b=b.indexOf(this.getLocation().host);return 8>=b&&0<=b?!0:!1},removeDomainIfIsInLink:function(b){b&&b.search&&-1!==b.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(b)&&((b=b.replace(/^.*\/\/[^/]+/,""))||
(b="/"));return b},findMediaUrlInNode:function(b){if(b){var e=b.nodeName.toLowerCase();if(-1!==M(["img","embed","video","audio"],e)&&t.findFirstNodeHavingAttributeWithValue(b,"src"))return b=t.findFirstNodeHavingAttributeWithValue(b,"src"),t.getAttributeValueFromNode(b,"src");if("object"===e&&t.hasNodeAttributeWithValue(b,"data"))return t.getAttributeValueFromNode(b,"data");if("object"===e){if((e=t.findNodesByTagName(b,"param"))&&e.length){var g;for(g=0;g<e.length;g++)if("movie"===t.getAttributeValueFromNode(e[g],
"name")&&t.hasNodeAttributeWithValue(e[g],"value"))return t.getAttributeValueFromNode(e[g],"value")}if((b=t.findNodesByTagName(b,"embed"))&&b.length)return this.findMediaUrlInNode(b[0])}}},trim:function(b){return b&&String(b)===b?b.replace(/^\s+|\s+$/g,""):b},isOrWasNodeInViewport:function(b){if(!b||!b.getBoundingClientRect||1!==b.nodeType)return!0;var e=b.getBoundingClientRect(),g=v.documentElement||{},h=0>e.top;h&&b.offsetTop&&(h=0<b.offsetTop+e.height);b=g.clientWidth;w.innerWidth&&b>w.innerWidth&&
(b=w.innerWidth);g=g.clientHeight;w.innerHeight&&g>w.innerHeight&&(g=w.innerHeight);return(0<e.bottom||h)&&0<e.right&&e.left<b&&(e.top<g||h)},isNodeVisible:function(b){var e=Oa(b);b=this.isOrWasNodeInViewport(b);return e&&b},buildInteractionRequestParams:function(b,e,g,h){var q="";b&&(q+="c_i="+C(b));e&&(q&&(q+="&"),q+="c_n="+C(e));g&&(q&&(q+="&"),q+="c_p="+C(g));h&&(q&&(q+="&"),q+="c_t="+C(h));return q},buildImpressionRequestParams:function(b,e,g){b="c_n="+C(b)+"&c_p="+C(e);g&&(b+="&c_t="+C(g));
return b},buildContentBlock:function(b){if(b){var e=this.findContentName(b),g=this.findContentPiece(b);b=this.findContentTarget(b);e=this.trim(e);g=this.trim(g);b=this.trim(b);return{name:e||"Unknown",piece:g||"Unknown",target:b||""}}},collectContent:function(b){if(!b||!b.length)return[];var e=[],g;for(g=0;g<b.length;g++){var h=this.buildContentBlock(b[g]);k(h)&&e.push(h)}return e},setLocation:function(b){this.location=b},getLocation:function(){var b=this.location||w.location;b.origin||(b.origin=
b.protocol+"//"+b.hostname+(b.port?":"+b.port:""));return b},toAbsoluteUrl:function(b){return b&&String(b)===b||""===b?""===b?this.getLocation().href:-1!==b.search(/^\/\//)?this.getLocation().protocol+b:-1!==b.search(/:\/\//)?b:0===b.indexOf("#")||0===b.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+b:0===b.search("^[a-zA-Z]{2,11}:")?b:-1!==b.search(/^\//)?this.getLocation().origin+b:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+b:b},isUrlToCurrentDomain:function(b){b=
this.toAbsoluteUrl(b);if(!b)return!1;var e=this.getLocation().origin;return e===b?!0:0===String(b).indexOf(e)?":"===String(b).substr(e.length,1)?!1:!0:!1},setHrefAttribute:function(b,e){b&&e&&t.setAnyAttribute(b,"href",e)},shouldIgnoreInteraction:function(b){var e=t.hasNodeAttribute(b,this.CONTENT_IGNOREINTERACTION_ATTR);b=t.hasNodeCssClass(b,this.CONTENT_IGNOREINTERACTION_CLASS);return e||b}};B(w,"beforeunload",function(){na("unload");if(Sa){do var b=new Date;while(b.getTimeAlias()<Sa)}},!1);(function(){var b;
v.addEventListener?B(v,"DOMContentLoaded",function g(){v.removeEventListener("DOMContentLoaded",g,!1);ma()}):v.attachEvent&&(v.attachEvent("onreadystatechange",function g(){"complete"===v.readyState&&(v.detachEvent("onreadystatechange",g),ma())}),v.documentElement.doScroll&&w===w.top&&function h(){if(!Qa){try{v.documentElement.doScroll("left")}catch(q){setTimeout(h,0);return}ma()}}());/WebKit/.test(ca.userAgent)&&(b=setInterval(function(){if(Qa||/loaded|complete/.test(v.readyState))clearInterval(b),
ma()},10));B(w,"load",ma,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;var Za=new Lb;var Kb={setTrackerUrl:1,setAPIUrl:1,setUserId:1,setSiteId:1,disableCookies:1,enableLinkTracking:1};for(pa=0;pa<_paq.length;pa++){var mb=_paq[pa][0];Kb[mb]&&(G(_paq[pa]),delete _paq[pa],1<Kb[mb]&&void 0!==console&&console&&console.error&&console.error("The method "+mb+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers'),
Kb[mb]++)}for(pa=0;pa<_paq.length;pa++)_paq[pa]&&G(_paq[pa]);_paq=new function(){return{push:G}};var sc={addPlugin:function(b,e){Pa[b]=e},getTracker:function(b,e){k(e)||(e=this.getAsyncTracker().getSiteId());k(b)||(b=this.getAsyncTracker().getTrackerUrl());return new Lb(b,e)},getAsyncTracker:function(){return Za}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return sc});return sc}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();
(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=Piwik)})();
"function"!==typeof piwik_log&&(piwik_log=function(l,k,m,u){function p(B){try{return eval("piwik_"+B)}catch(na){}}var G=Piwik.getTracker(m,k);G.setDocumentTitle(l);G.setCustomData(u);(l=p("tracker_pause"))&&G.setLinkTrackingTimer(l);(l=p("download_extensions"))&&G.setDownloadExtensions(l);(l=p("hosts_alias"))&&G.setDomains(l);(l=p("ignore_classes"))&&G.setIgnoreClasses(l);G.trackPageView();p("install_tracker")&&(piwik_track=function(B,na,ma,U){G.setSiteId(na);G.setTrackerUrl(ma);G.trackLink(B,U)},
G.enableLinkTracking())});
